### ISSUE TITLE
Mkdocs Automatic Site Building And Deploy

### ISSUE THREAD

**Issue by Richienb** [pinax/pinax#137]
I've noticed that you have setup your `.travis.yml` file to only check for build runtime errors but you can also deploy the site if the build succeeds

Just change the script section to:

```yaml
before_deploy:
  - pip install mkdocs
  - mkdocs build --verbose --clean --strict
```

And add a deploy section:

```yaml
deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master
```

Now follow these steps for setting the `github_token` variable in Travis CI

1. Go to the settings of your account
1. Click on `Developer settings`
1. Click on `Personal access tokens`
1. Click `Generate new token`
1. You may need to enter your Github password at this point
1. Name the token something under `Token description` (it doesn't matter)
1. Enable the `public_repo` scope/permission
1. Click `Generate token` at the bottom of the page
1. Go to the settings of the target Travis CI repository
1. Create an environmental variable with the following settings: | name: `github_token` | value: `Your Token` | Display value in build log: `No`
1. Press `add`

That's it. For more help, read my stackoverflow [Q&A](https://stackoverflow.com/questions/50892018/auto-build-an-mkdocs-documentation-in-travis-ci) or just ask below.
